// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/service.proto

package serviceconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	apiv1 "github.com/pranc1ngpegasus/coding-agent-playground/pkg/proto/api/v1"
	http "net/http"
	strings "strings"
)

const (
	GreetServiceName = "api.v1.GreetService"
)

const (
	GreetServiceGreetProcedure = "/api.v1.GreetService/Greet"
)

type GreetServiceClient interface {
	Greet(context.Context, *connect.Request[apiv1.GreetRequest]) (*connect.Response[apiv1.GreetResponse], error)
}

func NewGreetServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GreetServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &greetServiceClient{
		greet: connect.NewClient[apiv1.GreetRequest, apiv1.GreetResponse](
			httpClient,
			baseURL+GreetServiceGreetProcedure,
			opts...,
		),
	}
}

type greetServiceClient struct {
	greet *connect.Client[apiv1.GreetRequest, apiv1.GreetResponse]
}

func (c *greetServiceClient) Greet(ctx context.Context, req *connect.Request[apiv1.GreetRequest]) (*connect.Response[apiv1.GreetResponse], error) {
	return c.greet.CallUnary(ctx, req)
}

type GreetServiceHandler interface {
	Greet(context.Context, *connect.Request[apiv1.GreetRequest]) (*connect.Response[apiv1.GreetResponse], error)
}

func NewGreetServiceHandler(svc GreetServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	greetServiceGreetHandler := connect.NewUnaryHandler(
		GreetServiceGreetProcedure,
		svc.Greet,
		opts...,
	)
	return GreetServiceName, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GreetServiceGreetProcedure:
			greetServiceGreetHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

type UnimplementedGreetServiceHandler struct{}

func (UnimplementedGreetServiceHandler) Greet(context.Context, *connect.Request[apiv1.GreetRequest]) (*connect.Response[apiv1.GreetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.GreetService.Greet is not implemented"))
}
